version: '3.9'
services:
  tomcat:
    image: tomcat:9.0-jdk11
    container_name: tomcat-9
    ports:
      - 8080:8080
    environment:
      CATALINA_BASE: /usr/local/tomcat
    restart: always
    volumes:
    - ./build/libs/MedicalClinic.war:/usr/local/tomcat/webapps/MedicalClinic.war
    depends_on:
      - db
      - flyway
    networks:
      vpcbr:
        ipv4_address: 10.0.0.2

  flyway:
    container_name: flyway
    image: flyway/flyway:8.5-alpine
    command:
      -url=jdbc:postgresql://db:5432/med_clinic -schemas=public -user=admin -password=admin migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
      - .flyway.conf:/flyway/conf
    depends_on:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.0.0.3

  db:
    image: postgres:10-alpine
    container_name: postges-10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: med_clinic
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      vpcbr:
        ipv4_address: 10.0.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1